### ISSUE TITLE
panic: 3:15: expected expression (and 4 more errors)

### ISSUE THREAD

**Issue by wildsurfer** [dizzyfool/genna#1]
If you have table with dash symbol in it's name you will get this error:

```
getting info from database ...
running generator ...
panic: 3:15: expected expression (and 4 more errors)

goroutine 1 [running]:
github.com/dizzyfool/genna/cmd.glob..func1(0x17cf000, 0xc420112d20, 0x0, 0x6)
	/Users/kuzma/Documents/Workspace/go/src/github.com/dizzyfool/genna/cmd/root.go:94 +0x69e
github.com/spf13/cobra.(*Command).execute(0x17cf000, 0xc420010080, 0x6, 0x6, 0x17cf000, 0xc420010080)
	/Users/kuzma/Documents/Workspace/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x17cf000, 0xa, 0x151e300, 0x15311f5)
	/Users/kuzma/Documents/Workspace/go/src/github.com/spf13/cobra/command.go:852 +0x334
github.com/spf13/cobra.(*Command).Execute(0x17cf000, 0x0, 0xc42010f150)
	/Users/kuzma/Documents/Workspace/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/dizzyfool/genna/cmd.Execute()
	/Users/kuzma/Documents/Workspace/go/src/github.com/dizzyfool/genna/cmd/root.go:106 +0x31
main.main()
	/Users/kuzma/Documents/Workspace/go/src/github.com/dizzyfool/genna/main.go:20 +0x20
```

**Comment by wildsurfer** [comment]
is it fixed? :)

**Comment by dizzyfool** [comment]
It should be :) I've checked on table with name "user-accounts" and it generates now as UserAccount
